version: '3.0'

services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "log"
      RABBITMQ_DEFAULT_PASS: "log"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
      - 5672
    tty: true

  master:
    build:
      context: ./master
    depends_on:
      - rabbit
    ports:
      - 80:8080
    expose:
      - 80
    environment:
      - server.port=8080
      - spring.rabbitmq.host=rabbit

  slave:
    build:
      context: ./slave
    depends_on:
      - rabbit
    environment:
      - server.port=8080
      - spring.rabbitmq.host=rabbit
